### ISSUE TITLE
Whats up with the asdfasdfasdf class?

### ISSUE THREAD

**Issue by reggi** [IanGallacher/LearnToCode#9]
https://github.com/IanGallacher/LearnToCode/blob/master/index.php#L32

**Comment by IanGallacher** [comment]
That is a poorly named 'temporary' class directly related to the issue I was asking about. I forgot to change it to a readable name before I committed. 

Originally I was looking for #codecontainer>#sortable in https://github.com/IanGallacher/LearnToCode/blob/master/index.php#L317
(it looks like I still am, that is probably the issue)

That would mean that it would find all the lists, and nested lists, all the way down the command block. 

So I created asdfasdfasdf on only the top level sortable element to see if it would fix the bug. 

At the time it did not.

**Comment by IanGallacher** [comment]
Just tested again, even with the selector looking for asdfasdfasdf it did not fix the issue. 

The bug in question can be found here. 
![image](https://cloud.githubusercontent.com/assets/7298650/6162741/6dad0664-b23c-11e4-9b05-6d9aa41fff85.png)

**Comment by reggi** [comment]
I don't know what the intended result is? Is there still a problem with upon running gathering the tasks?

**Comment by IanGallacher** [comment]
Yes. The intended result is for the player character not to rotate unless the tile in front of him is blank/a wall. 

If the values selected were, "Tile in Front", "Equals", and "Walkable" then the character should rotate, as the tile in front of him is a floor tile.

**Comment by reggi** [comment]
Our level 3's look different and my `if` statement block looks all messed up. Hmm

![screen shot 2015-02-12 at 1 37 44 am](https://cloud.githubusercontent.com/assets/296798/6162874/cc633ff0-b257-11e4-876b-2965750d9d26.png)

**Comment by IanGallacher** [comment]
My level 3 is your level 4, I changed that after the commit.
